# Generated by Django 5.1.3 on 2024-11-15 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=100)),
                ('news_desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshopapp.newscategory')),
            ],
        ),
    ]
